version: "3.8"
services:
  backend:
    ports:
      - 8001:8000
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - ./backend/static/:/app/static/
      - ./backend/media/:/app/meia/
    environment:
      - DEBUG=False
      - LOG_LEVEL=info
      - DOMAIN=${DOMAIN-localhost}
    restart: on-failure
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: sh scripts/start-reload.sh

  nginx:
    ports:
      - 988:80
    build:
      context: ./backend
      dockerfile: nginx_static_conf/nginx.dockerfile
    volumes:
      - ./backend/static/:/app/static/
      - ./backend/media/:/app/media/

  db:
    env_file:
      - .env
    image: postgres:12
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdatapm_tools
      - TZ=Europe/Kiev
      - PGTZ=Europe/Kiev
